### ISSUE TITLE
Can't upload files net:ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by Hammit** [ErugoOSS/Erugo#169]
I am using Erugo 0.2.3
I have it running with nginx-proxy-manager. I have followed the Erugo documentation for how to configure NPM for use with Erugo.

After creating an admin account and providing the SMTP settings etc for the system I have tested uploads of a small 2MB image. Every time it fails. The initial upload fails. Subsequent uploads of the same image are detected as a resume and upon resuming the upload, the resumes always fail. Even starting "Fresh" it fails.

<img width="657" height="334" alt="Image" src="https://github.com/user-attachments/assets/32a3d663-886c-4b1f-8ba1-beae39a2a332" />

<img width="846" height="1053" alt="Image" src="https://github.com/user-attachments/assets/8989499c-50ea-4729-9d58-976746d9f9c0" />

<img width="1609" height="1567" alt="Image" src="https://github.com/user-attachments/assets/72f1f56a-1396-4c18-88be-0d314226a77b" />

**Comment by Hammit** [comment]
I clicked Application > Storage > Clear Site data

<img width="2258" height="1965" alt="Image" src="https://github.com/user-attachments/assets/2248c877-ee12-48e5-8d7c-3bfa032e3b24" />

**Comment by Hammit** [comment]
Yes, it logged me out. I have not been able to upload a single file. This is my first test file upload. Are there application logs to inspect? Is it a problem with Erugo, or the fact that I'm using nginx-proxy-manager?

**Comment by Hammit** [comment]
I tried uploading a different image (PNG instead of JPG) and it had the same problem. I now successfully uploaded a .json file and it seemed to work

**Comment by DeanWard** [comment]
One thing i notice is that the error messages says you're on port 8000 but the uploads don't seem to be going to that port and the connection is being refused. Its likely a configuration problem, we just need to figure out exactly what is wrong. the port thing is a clue though and https://hammit-erugo.duckdns.org doesn't appear to respond at all.

logs are in the logs folder inside storage mount

**Comment by Hammit** [comment]
8000 is correct. I have port 8000 port forwarding on my router to port 443 on my internal network. The container handling port 443 is nginx-proxy-manager. But as I just found out, that shouldn't be a problem because I just uploaded a .json file successfully and got a share link for that. It's just images (so far) that aren't uploading. The .json file was very small, and the images were a few megabytes.

**Comment by DeanWard** [comment]
I have found a potential issue that may be causing your problem. The system invalidates cached fingerprints if the domain and scheme don't match but it doesn't take port into account. i've pushed a patch for this. Please try re-pulling the container image  (0.2.4) and try again 🤞

Just https is fine, this is all to do with the weird port setup I think!

**Comment by Hammit** [comment]
That didn't work. I stopped the container. Pulled 0.2.4. Restarted container with 0.2.4. Cleared Application site data. Re-logged in and tested image upload. Same problem. Here's a relevant snippet from Docker...

Notice the urls still have the port missing?

```
erugo  | 2025/12/27 10:51:21.895140 level=INFO event=RequestIncoming method=POST path="" requestId=""
erugo  | 2025/12/27 10:51:21.895215 level=DEBUG event=HookInvocationStart type=pre-create id=""
erugo  | 2025/12/27 10:51:21.895140 level=INFO event=RequestIncoming method=POST path="" requestId=""
erugo  | 2025/12/27 10:51:21.895215 level=DEBUG event=HookInvocationStart type=pre-create id=""
erugo  | 2025/12/27 10:51:21.979515 level=DEBUG event=HookInvocationFinish type=pre-create id=""
erugo  | 2025/12/27 10:51:21.979632 level=INFO event=UploadCreated method=POST path="" requestId="" id=464e8965ae3fc278e88fb71d92fdfde5 size=2093476 url=https://hammit-erugo.duckdns.org/files/464e8965ae3fc278e88fb71d92fdfde5
erugo  | 2025/12/27 10:51:21.979647 level=INFO event=ResponseOutgoing method=POST path="" requestId="" id=464e8965ae3fc278e88fb71d92fdfde5 status=201 body=""
erugo  | 2025/12/27 10:51:21.979747 level=DEBUG event=HookInvocationStart type=post-create id=464e8965ae3fc278e88fb71d92fdfde5
erugo  | 2025/12/27 10:51:21.979515 level=DEBUG event=HookInvocationFinish type=pre-create id=""
erugo  | 2025/12/27 10:51:21.979632 level=INFO event=UploadCreated method=POST path="" requestId="" id=464e8965ae3fc278e88fb71d92fdfde5 size=2093476 url=https://hammit-erugo.duckdns.org/files/464e8965ae3fc278e88fb71d92fdfde5
erugo  | 2025/12/27 10:51:21.979647 level=INFO event=ResponseOutgoing method=POST path="" requestId="" id=464e8965ae3fc278e88fb71d92fdfde5 status=201 body=""
erugo  | 2025/12/27 10:51:21.979747 level=DEBUG event=HookInvocationStart type=post-create id=464e8965ae3fc278e88fb71d92fdfde5
erugo  | 2025/12/27 10:51:22.061198 level=DEBUG event=HookInvocationFinish type=post-create id=464e8965ae3fc278e88fb71d92fdfde5
erugo  | 2025/12/27 10:51:22.061198 level=DEBUG event=HookInvocationFinish type=post-create id=464e8965ae3fc278e88fb71d92fdfde5
```

**Comment by DeanWard** [comment]
This is highly frustrating! Could you jump on discord and ping me please?
